//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockServiceConsumer.localhost {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GraphData", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class GraphData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDateRange", ReplyAction="http://tempuri.org/IService/GetDateRangeResponse")]
        StockServiceConsumer.localhost.GraphData[] GetDateRange(System.DateTime first, System.DateTime last);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetDateRange", ReplyAction="http://tempuri.org/IService/GetDateRangeResponse")]
        System.Threading.Tasks.Task<StockServiceConsumer.localhost.GraphData[]> GetDateRangeAsync(System.DateTime first, System.DateTime last);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcMovingAverages", ReplyAction="http://tempuri.org/IService/CalcMovingAveragesResponse")]
        StockServiceConsumer.localhost.GraphData[] CalcMovingAverages(System.DateTime firstDate, System.DateTime lastDate, int numDays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/CalcMovingAverages", ReplyAction="http://tempuri.org/IService/CalcMovingAveragesResponse")]
        System.Threading.Tasks.Task<StockServiceConsumer.localhost.GraphData[]> CalcMovingAveragesAsync(System.DateTime firstDate, System.DateTime lastDate, int numDays);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : StockServiceConsumer.localhost.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<StockServiceConsumer.localhost.IService>, StockServiceConsumer.localhost.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StockServiceConsumer.localhost.GraphData[] GetDateRange(System.DateTime first, System.DateTime last) {
            return base.Channel.GetDateRange(first, last);
        }
        
        public System.Threading.Tasks.Task<StockServiceConsumer.localhost.GraphData[]> GetDateRangeAsync(System.DateTime first, System.DateTime last) {
            return base.Channel.GetDateRangeAsync(first, last);
        }
        
        public StockServiceConsumer.localhost.GraphData[] CalcMovingAverages(System.DateTime firstDate, System.DateTime lastDate, int numDays) {
            return base.Channel.CalcMovingAverages(firstDate, lastDate, numDays);
        }
        
        public System.Threading.Tasks.Task<StockServiceConsumer.localhost.GraphData[]> CalcMovingAveragesAsync(System.DateTime firstDate, System.DateTime lastDate, int numDays) {
            return base.Channel.CalcMovingAveragesAsync(firstDate, lastDate, numDays);
        }
    }
}
